### ISSUE TITLE
Model MarketingAnalyzers in Power BI

### ISSUE THREAD

**Issue by AleACR** [Microsoft/Dynamics-365-for-Marketing---Power-BI-Reporting#3]
**Describe the bug**
Hello, I am trying to implement the powerbi model of marketing analyzers downloaded from gibhub, and I can see jouney created, but the table Emailopened and others tables, does not contain data. In dynamics the route or campaign created, by sending an email, which was opened and this is registeredin dynamics in form correct, but not see register in the table EmailOpened.

Please any help

Thank you
**Screenshots**
![image](https://user-images.githubusercontent.com/53618803/62380886-31bfb280-b518-11e9-9a0e-4da42b821afd.png)

**Comment by cabeln** [comment]
Please read this post on how to `[control the interaction data load.](http://powerbi.dynamicsmarketing.org/controlling-the-marketing-reporting-data-load/)`
Hope this solves the issue
