### ISSUE TITLE
Issue with Timestamp in EmailClicked table

### ISSUE THREAD

**Issue by DecoyOtter** [Microsoft/Dynamics-365-for-Marketing---Power-BI-Reporting#4]
Hi,

I am getting an error from the EmailClicked table where it appears the Timestamp is invalid.

Seems like the data being added to the table is out of sync with the columns in the table?

Error:
![image](https://user-images.githubusercontent.com/46342392/64576225-02278400-d3bb-11e9-9e0d-c2533921c512.png)

Data in the table (note the values against the columns)
![0OYeITbGiG](https://user-images.githubusercontent.com/46342392/64576241-11a6cd00-d3bb-11e9-90a2-9e63a31a9f27.png)

**Comment by cabeln** [comment]
Hello, 
Thank you for reporting and for your comment!
The reason for this was that some of the reports had in the  _Regional Settings_ of the Options in Power BI for the _Current File_ a different local then English US set which lead to problems when parsing the Timestamp value in the interaction data. 
The Timestamp format is currently not in universal data format but in date time timezone format for en-US. Until this is resolved in the blob storage data, the local of the power bi file must be set to en-US.
This is now resolved in the latest version of the reports and templates on GitHub in Master.
